### ISSUE TITLE
Error: undefined method 'unix' for HTTP::Client.class

### ISSUE THREAD

**Issue by speg** [aca-labs/crystal-docker#4]
How do we make a `HTTP::Client` that uses a unix socket?

**Comment by caspiano** [comment]
Here's the way you'd go about it in recent versions of crystal.

```crystal
require "http"
require "socket"

socket = UNIXSocket.new("/tmp/myapp.sock")
client = HTTP::Client.new(io: socket)
```

However, this should already be happening in the library.
Which crystal version are you on?

**Comment by speg** [comment]
1.0

I was just confused by this line https://github.com/aca-labs/crystal-docker/blob/master/src/docker/api/api_client.cr#L33

and where `.unix` came from.

**Comment by speg** [comment]
I see it was extended here! 

https://github.com/aca-labs/crystal-docker/blob/master/src/core_ext/http/client.cr#L12

Cool beans 😎
